"""Mise à jour de la table buffet_items

Revision ID: f349ff2d656f
Revises: 84cb7b78d9d2
Create Date: 2025-05-31 10:17:40.153783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f349ff2d656f'
down_revision = '84cb7b78d9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buffet_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('content_id', sa.String(length=36), nullable=False))
        batch_op.drop_constraint(batch_op.f('buffet_items_food_id_fkey'), type_='foreignkey')
        batch_op.drop_column('food_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('buffet_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('buffet_items_food_id_fkey'), 'foods', ['food_id'], ['id'])
        batch_op.drop_column('content_id')
        batch_op.drop_column('content_type')

    # ### end Alembic commands ###
